"""Generate every run config from one table. `python make_configs.py`.

The table *is* the experiment plan: one row = one run = one committed YAML.
Exactly one thing changes per row against the v3 reference (50/50, r=16, 2ep,
2e-4) — that's what makes the results attributable instead of anecdotal.

Run them in priority order (RUNBOOK.md); the curve needs v1-v5, everything
after that is an ablation you can stop at any point without wasting the ones
already done.
"""
import os

REFERENCE = dict(data="mix_50_50", epochs=2, r=16, lr="2.0e-4", seed=0,
                 base="unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit", max_steps=-1)

# A full run (epochs=2 over mix_50_50) takes ~1h on a Kaggle T4x2. max_steps
# caps total optimizer steps so a run stops early regardless of epoch count —
# use it for a quick, cheap look at a result before spending a full hour on it.
BUDGET_STEPS = 60  # ~10-15 min/run

# name              what it isolates                          overrides
RUNS = [
    ("v1_mix10", "curve anchor: minimum abstain dose",         dict(data="mix_10_90")),
    ("v2_mix25", "curve point",                                dict(data="mix_25_75")),
    ("v3_mix50", "reference run",                              dict()),
    ("v4_mix75", "curve point",                                dict(data="mix_75_25")),
    ("v5_mix90", "curve anchor: near-total abstain",           dict(data="mix_90_10")),
    ("v6_1epoch", "dosage — Lean found epochs non-monotonic",  dict(epochs=1)),
    ("v7_3epoch", "dosage, other direction",                   dict(epochs=3)),
    ("v8_rank8", "capacity: does a smaller LoRA refuse less?", dict(r=8)),
    ("v9_rank32", "capacity, other direction",                 dict(r=32)),
    ("v10_lr1e4", "lower LR — is over-refusal just overfit?",  dict(lr="1.0e-4")),
    ("v11_bare_reason", "ablation: is naming the reason worth anything?",
     dict(data="mix_50_50_bare")),
    # Seed replicates of the reference. Without these, "mix A beats mix B by 4
    # points" is unfalsifiable — you cannot tell a real gap from run-to-run
    # noise, and the whole curve rests on gaps of that size.
    ("v12_seed1", "run-to-run variance of the reference recipe", dict(seed=1)),
    ("v13_seed2", "run-to-run variance of the reference recipe", dict(seed=2)),
    # Does the finding survive a size change, or is it a 1.5B artifact? Scored
    # against its own 3B baselines, never against the 1.5B ones.
    ("v14_qwen3b", "does the recipe hold at 3B?",
     dict(base="unsloth/Qwen2.5-3B-Instruct-bnb-4bit")),
    # v14 came back as the only arm that escaped the tradeoff — which makes it
    # the one result that must not rest on a single seed. At 1.5B the seed
    # spread was 18.5 pp on over-refusal, wide enough to manufacture exactly
    # this kind of finding. Same bar for the good news as for the bad.
    ("v14_seed1", "seed replicate of the 3B run — the headline result held to its own standard",
     dict(base="unsloth/Qwen2.5-3B-Instruct-bnb-4bit", seed=1)),
    # Budgeted previews (~10-15 min each vs ~1h full) — max_steps cuts every
    # run short so you can see the direction of a result before spending a
    # full hour confirming it.
    ("v15_budget_mix25", "cheap look at a curve point (v2 preview)",
     dict(data="mix_25_75", max_steps=BUDGET_STEPS)),
    ("v16_budget_mix75", "cheap look at a curve point (v4 preview)",
     dict(data="mix_75_25", max_steps=BUDGET_STEPS)),
    ("v17_budget_lr5e5", "cheap look at a lower LR than v10 tried",
     dict(lr="5.0e-5", max_steps=BUDGET_STEPS)),
]

TEMPLATE = """# {name} — {why}
# Generated by make_configs.py. Edit the table there, not this file.
base_model: {base}
seed: {seed}

lora:
  r: {r}
  alpha: {alpha}
  dropout: 0
  target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]

train:
  data_path: data/{data}.jsonl
  output_dir: runs/{name}
  epochs: {epochs}
  batch_size: 2
  grad_accum: 8
  lr: {lr}
  max_seq_len: 1024
  val_fraction: 0.05
  max_steps: {max_steps}
"""


def main(out_dir="configs"):
    os.makedirs(out_dir, exist_ok=True)
    for name, why, overrides in RUNS:
        cfg = dict(REFERENCE, **overrides, name=name, why=why)
        cfg["alpha"] = cfg["r"]  # alpha=r throughout: one capacity knob, not two
        path = os.path.join(out_dir, f"{name}.yaml")
        with open(path, "w", encoding="utf-8") as f:
            f.write(TEMPLATE.format(**cfg))
        print("wrote", path)
    print(f"\n{len(RUNS)} runs, in the order they earn their keep:")
    print("  1. curve      : v3, v2, v4, v1, v5")
    print("  2. variance   : v12, v13   (do these before believing any small gap)")
    print("  3. dosage     : v6, v7")
    print("  4. capacity/LR: v8, v9, v10")
    print("  5. ablation   : v11")
    print("  6. scale      : v14 (3B — also needs its own base/prompt eval arms)")


if __name__ == "__main__":
    main()
